on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  contents: write
  security-events: write
  packages: write
  id-token: write

jobs:
  build:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/gradle-25.yaml@main
    secrets: inherit
    with:
      app: 'teamsykmelding-pik'
      team: 'teamsykmelding'
