name: Deploy app to dev and prod
on: push

jobs:
  jar-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/jar-app.yaml@main
    secrets: inherit
    with:
      app: teamsykmelding-pik
